recertOperator : gcr.io/williams-heavy-industries/recert-operator:latest
recertNginx: gcr.io/williams-heavy-industries/recert-nginx:latest
recertCertbot: gcr.io/williams-heavy-industries/recert-certbot:latest
